"use client";

import { useCallback, useState } from "react";

import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { applyPatch, brainSetApiKey, proposeNote } from "@/lib/api/tools";

import { WelcomeStep } from "./steps/welcome";
import { VaultLocationStep } from "./steps/vault-location";
import { ApiKeyStep } from "./steps/api-key";
import { BLANK_THEME, StartingThemeStep } from "./steps/starting-theme";
import { BrainMdStep, DEFAULT_BRAIN_MD } from "./steps/brain-md";
import { ClaudeDesktopStep } from "./steps/claude-desktop";

const TOTAL_STEPS = 6;

export interface WizardProps {
  /**
   * Fires when the user either reaches the last step and clicks
   * "Start using brain", or bails via the "Already set up" escape hatch on
   * step 1. The parent is responsible for persisting the setup-done flag
   * and routing to /chat.
   */
  onDone: () => void;
}

/**
 * Setup wizard — 6 steps, stepped progress, Back/Next nav. State lives in
 * local `useState` per Checkpoint 3 decision: Zustand persistence is overkill
 * for a one-shot flow.
 *
 * **Vault seeding exception.** Checkpoint 3 decision (2) — when the user
 * picks a theme and advances, we call `proposeNote(...)` then immediately
 * `applyPatch(...)` without going through the pending queue. Same for
 * BRAIN.md on step 5 save. This is a DOCUMENTED EXCEPTION to the "every LLM
 * write staged" invariant; it only runs during setup, and the content is
 * user-driven (no LLM generated bytes).
 */
export function Wizard({ onDone }: WizardProps) {
  const [step, setStep] = useState(1);
  const [vaultPath, setVaultPath] = useState("~/Documents/brain");
  const [apiKey, setApiKey] = useState("");
  // Track whether the api-key value currently in ``apiKey`` has been
  // persisted to ``<vault>/.brain/secrets.env``. The Test button on
  // step 3 saves + ping-tests in one shot; if the user types a key but
  // skips the Test button, ``handleNext`` falls back to persisting on
  // step 3 → step 4 advance (issue #20).
  const [apiKeySaved, setApiKeySaved] = useState(false);
  // Plan 10 Task 8: theme is now a domain slug (or ``BLANK_THEME``)
  // since the cards are driven by ``Config.domains`` rather than a
  // hardcoded enum.
  const [theme, setTheme] = useState<string>(BLANK_THEME);
  const [brainMd, setBrainMd] = useState(DEFAULT_BRAIN_MD);
  const [busy, setBusy] = useState(false);

  // Bridge for the api-key step: the step's Test button saves+pings
  // directly via ``brain_set_api_key``; signal that here so we don't
  // double-save on advance. Wrapping the prop setter rather than
  // exposing ``setApiKeySaved`` to the step keeps the state contract
  // minimal — the step only knows about value + onChange + onSaved.
  const handleApiKeyChange = useCallback((value: string) => {
    setApiKey(value);
    setApiKeySaved(false);
  }, []);
  const handleApiKeySaved = useCallback(() => {
    setApiKeySaved(true);
  }, []);

  const canContinue =
    step !== 2 ? true : vaultPath.trim().length > 0;

  const seedTheme = useCallback(async (pick: string) => {
    if (pick === BLANK_THEME) return;
    // Plan 10 Task 8: built-in slugs (research / work) keep the v0.1
    // seed copy; user-added slugs get a generic stub. ``personal``
    // never reaches this path because the picker filters it out.
    const seed = THEME_SEEDS[pick] ?? genericSeed(pick);
    // `proposeNote` throws ApiError on non-2xx; let errors bubble — the
    // wizard stays in-place and the user can retry by re-clicking Continue.
    const res = await proposeNote({
      path: `${pick}/index.md`,
      content: seed,
      reason: "setup wizard seed",
    });
    const patchId = res.data?.patch_id;
    if (patchId) {
      await applyPatch({ patch_id: patchId });
    }
  }, []);

  const seedBrainMd = useCallback(async (content: string) => {
    const trimmed = content.trim();
    if (!trimmed) return;
    const res = await proposeNote({
      path: "BRAIN.md",
      content,
      reason: "setup wizard seed",
    });
    const patchId = res.data?.patch_id;
    if (patchId) {
      await applyPatch({ patch_id: patchId });
    }
  }, []);

  async function handleNext() {
    if (busy) return;
    if (step === 3) {
      // Issue #20: persist the api key on advance if the user typed a
      // value but didn't click the in-step "Test" button (which saves
      // + pings in one shot). Idempotent — re-sending the same key is
      // a no-op on the backend's side; the step's local "saved" flag
      // just lets us short-circuit the round-trip when the Test
      // button already did the work.
      if (apiKey.trim().length > 0 && !apiKeySaved) {
        setBusy(true);
        try {
          await brainSetApiKey({ provider: "anthropic", api_key: apiKey });
          setApiKeySaved(true);
        } finally {
          setBusy(false);
        }
      }
    } else if (step === 4) {
      setBusy(true);
      try {
        await seedTheme(theme);
      } finally {
        setBusy(false);
      }
    } else if (step === 5) {
      setBusy(true);
      try {
        await seedBrainMd(brainMd);
      } finally {
        setBusy(false);
      }
    }
    setStep((s) => Math.min(TOTAL_STEPS, s + 1));
  }

  function handleBack() {
    setStep((s) => Math.max(1, s - 1));
  }

  function handleSkipStep() {
    setStep((s) => Math.min(TOTAL_STEPS, s + 1));
  }

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="setup-wizard-heading"
      className="relative flex min-h-screen w-full items-center justify-center bg-background p-6"
    >
      <div className="relative w-full max-w-2xl rounded-xl border border-input bg-card p-10 shadow-lg">
        <p
          id="setup-wizard-heading"
          className="mb-6 text-xs uppercase tracking-[0.2em] text-muted-foreground"
        >
          Step {step} of {TOTAL_STEPS}
        </p>

        {step === 1 && <WelcomeStep />}
        {step === 2 && (
          <VaultLocationStep value={vaultPath} onChange={setVaultPath} />
        )}
        {step === 3 && (
          <ApiKeyStep
            value={apiKey}
            onChange={handleApiKeyChange}
            onSaved={handleApiKeySaved}
          />
        )}
        {step === 4 && (
          <StartingThemeStep pick={theme} onPick={setTheme} />
        )}
        {step === 5 && (
          <BrainMdStep value={brainMd} onChange={setBrainMd} />
        )}
        {step === 6 && <ClaudeDesktopStep />}

        <div
          aria-hidden="true"
          className="mt-8 flex items-center justify-center gap-2"
        >
          {Array.from({ length: TOTAL_STEPS }).map((_, i) => {
            const n = i + 1;
            return (
              <span
                key={i}
                className={cn(
                  "h-1.5 w-6 rounded-full transition-colors",
                  n === step
                    ? "bg-primary"
                    : n < step
                    ? "bg-primary/60"
                    : "bg-muted",
                )}
              />
            );
          })}
        </div>

        <div className="mt-6 flex items-center justify-between">
          <div>
            {step > 1 && (
              <Button
                type="button"
                variant="ghost"
                onClick={handleBack}
                disabled={busy}
              >
                ← Back
              </Button>
            )}
          </div>
          <div className="flex items-center gap-3">
            {step > 1 && step < TOTAL_STEPS && (
              <button
                type="button"
                onClick={handleSkipStep}
                disabled={busy}
                className="text-xs text-muted-foreground hover:text-foreground disabled:opacity-50"
              >
                Skip this →
              </button>
            )}
            {step < TOTAL_STEPS ? (
              <Button
                type="button"
                size="lg"
                onClick={handleNext}
                disabled={!canContinue || busy}
              >
                Continue
              </Button>
            ) : (
              <Button type="button" size="lg" onClick={onDone} disabled={busy}>
                Start using brain
              </Button>
            )}
          </div>
        </div>

        {step === 1 && (
          <div className="absolute bottom-5 right-8">
            <Button
              type="button"
              variant="link"
              size="sm"
              onClick={onDone}
              className="text-xs text-muted-foreground"
            >
              Already set up → open app
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}

/**
 * Seed content for the v0.1 built-in starting themes. Kept inline — this
 * is setup-wizard-specific copy, not something that belongs in brain_core.
 * User-added slugs (Plan 10) fall through to ``genericSeed()`` below.
 */
const THEME_SEEDS: Record<string, string> = {
  research: `# Research

Reading notes, paper summaries, and questions to chase down.

## Recent

_No notes yet. Drop a PDF or paste a URL to start._
`,
  work: `# Work

Calls, deals, customers, decisions — the day job.

## Recent

_No notes yet._
`,
};

/** Plan 10 Task 8: generic index seed for user-added domain slugs. */
function genericSeed(slug: string): string {
  const title = slug
    .split(/[-_]/)
    .filter(Boolean)
    .map((p) => p[0]!.toUpperCase() + p.slice(1))
    .join(" ");
  return `# ${title}

Notes for ${title}.

## Recent

_No notes yet._
`;
}
