"use client";

import { useCallback, useState } from "react";

import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { applyPatch, proposeNote } from "@/lib/api/tools";

import { WelcomeStep } from "./steps/welcome";
import { VaultLocationStep } from "./steps/vault-location";
import { ApiKeyStep } from "./steps/api-key";
import {
  StartingThemeStep,
  type ThemeKey,
} from "./steps/starting-theme";
import { BrainMdStep, DEFAULT_BRAIN_MD } from "./steps/brain-md";
import { ClaudeDesktopStep } from "./steps/claude-desktop";

const TOTAL_STEPS = 6;

export interface WizardProps {
  /**
   * Fires when the user either reaches the last step and clicks
   * "Start using brain", or bails via the "Already set up" escape hatch on
   * step 1. The parent is responsible for persisting the setup-done flag
   * and routing to /chat.
   */
  onDone: () => void;
}

/**
 * Setup wizard — 6 steps, stepped progress, Back/Next nav. State lives in
 * local `useState` per Checkpoint 3 decision: Zustand persistence is overkill
 * for a one-shot flow.
 *
 * **Vault seeding exception.** Checkpoint 3 decision (2) — when the user
 * picks a theme and advances, we call `proposeNote(...)` then immediately
 * `applyPatch(...)` without going through the pending queue. Same for
 * BRAIN.md on step 5 save. This is a DOCUMENTED EXCEPTION to the "every LLM
 * write staged" invariant; it only runs during setup, and the content is
 * user-driven (no LLM generated bytes).
 */
export function Wizard({ onDone }: WizardProps) {
  const [step, setStep] = useState(1);
  const [vaultPath, setVaultPath] = useState("~/Documents/brain");
  // TODO(plan-07 task 25 sweep): wire apiKey to `configSet` once the setup
  // flow can bootstrap a backend token independently.
  const [apiKey, setApiKey] = useState("");
  const [theme, setTheme] = useState<ThemeKey>("blank");
  const [brainMd, setBrainMd] = useState(DEFAULT_BRAIN_MD);
  const [busy, setBusy] = useState(false);

  const canContinue =
    step !== 2 ? true : vaultPath.trim().length > 0;

  const seedTheme = useCallback(async (pick: ThemeKey) => {
    if (pick === "blank") return;
    const seed = THEME_SEEDS[pick];
    // `proposeNote` throws ApiError on non-2xx; let errors bubble — the
    // wizard stays in-place and the user can retry by re-clicking Continue.
    const res = await proposeNote({
      path: `${pick}/index.md`,
      content: seed,
      reason: "setup wizard seed",
    });
    const patchId = res.data?.patch_id;
    if (patchId) {
      await applyPatch({ patch_id: patchId });
    }
  }, []);

  const seedBrainMd = useCallback(async (content: string) => {
    const trimmed = content.trim();
    if (!trimmed) return;
    const res = await proposeNote({
      path: "BRAIN.md",
      content,
      reason: "setup wizard seed",
    });
    const patchId = res.data?.patch_id;
    if (patchId) {
      await applyPatch({ patch_id: patchId });
    }
  }, []);

  async function handleNext() {
    if (busy) return;
    if (step === 4) {
      setBusy(true);
      try {
        await seedTheme(theme);
      } finally {
        setBusy(false);
      }
    } else if (step === 5) {
      setBusy(true);
      try {
        await seedBrainMd(brainMd);
      } finally {
        setBusy(false);
      }
    }
    setStep((s) => Math.min(TOTAL_STEPS, s + 1));
  }

  function handleBack() {
    setStep((s) => Math.max(1, s - 1));
  }

  function handleSkipStep() {
    setStep((s) => Math.min(TOTAL_STEPS, s + 1));
  }

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="setup-wizard-heading"
      className="relative flex min-h-screen w-full items-center justify-center bg-background p-6"
    >
      <div className="relative w-full max-w-2xl rounded-xl border border-input bg-card p-10 shadow-lg">
        <p
          id="setup-wizard-heading"
          className="mb-6 text-xs uppercase tracking-[0.2em] text-muted-foreground"
        >
          Step {step} of {TOTAL_STEPS}
        </p>

        {step === 1 && <WelcomeStep />}
        {step === 2 && (
          <VaultLocationStep value={vaultPath} onChange={setVaultPath} />
        )}
        {step === 3 && <ApiKeyStep value={apiKey} onChange={setApiKey} />}
        {step === 4 && (
          <StartingThemeStep pick={theme} onPick={setTheme} />
        )}
        {step === 5 && (
          <BrainMdStep value={brainMd} onChange={setBrainMd} />
        )}
        {step === 6 && <ClaudeDesktopStep />}

        <div
          aria-hidden="true"
          className="mt-8 flex items-center justify-center gap-2"
        >
          {Array.from({ length: TOTAL_STEPS }).map((_, i) => {
            const n = i + 1;
            return (
              <span
                key={i}
                className={cn(
                  "h-1.5 w-6 rounded-full transition-colors",
                  n === step
                    ? "bg-primary"
                    : n < step
                    ? "bg-primary/60"
                    : "bg-muted",
                )}
              />
            );
          })}
        </div>

        <div className="mt-6 flex items-center justify-between">
          <div>
            {step > 1 && (
              <Button
                type="button"
                variant="ghost"
                onClick={handleBack}
                disabled={busy}
              >
                ← Back
              </Button>
            )}
          </div>
          <div className="flex items-center gap-3">
            {step > 1 && step < TOTAL_STEPS && (
              <button
                type="button"
                onClick={handleSkipStep}
                disabled={busy}
                className="text-xs text-muted-foreground hover:text-foreground disabled:opacity-50"
              >
                Skip this →
              </button>
            )}
            {step < TOTAL_STEPS ? (
              <Button
                type="button"
                size="lg"
                onClick={handleNext}
                disabled={!canContinue || busy}
              >
                Continue
              </Button>
            ) : (
              <Button type="button" size="lg" onClick={onDone} disabled={busy}>
                Start using brain
              </Button>
            )}
          </div>
        </div>

        {step === 1 && (
          <div className="absolute bottom-5 right-8">
            <Button
              type="button"
              variant="link"
              size="sm"
              onClick={onDone}
              className="text-xs text-muted-foreground"
            >
              Already set up → open app
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}

/**
 * Seed content for the 3 non-blank starting themes. Kept inline — this is
 * setup-wizard-specific copy, not something that belongs in brain_core.
 */
const THEME_SEEDS: Record<Exclude<ThemeKey, "blank">, string> = {
  research: `# Research

Reading notes, paper summaries, and questions to chase down.

## Recent

_No notes yet. Drop a PDF or paste a URL to start._
`,
  work: `# Work

Calls, deals, customers, decisions — the day job.

## Recent

_No notes yet._
`,
  personal: `# Personal

Journal, ideas, and things that don't fit anywhere else.

## Recent

_No notes yet._
`,
};
