"use client";

import * as React from "react";

import { useDomains } from "@/lib/hooks/use-domains";
import { cn } from "@/lib/utils";

/**
 * Starting-theme step (4 / 6) — Plan 10 Task 8.
 *
 * The v0.1 wizard hardcoded the picker to one of
 * ``{research, work, personal, blank}``. Plan 10 makes the cards
 * structurally driven by ``Config.domains`` (via ``useDomains``):
 *
 *   * One card per non-``personal`` configured domain. ``personal`` is
 *     never seeded from setup — D5 keeps it privacy-railed and the
 *     user's first personal note should be written deliberately, not
 *     auto-generated by the wizard.
 *
 *   * A "Blank" sentinel stays as the don't-seed-anything escape
 *     hatch. Its key is ``BLANK_THEME`` so the wizard's seed step
 *     can short-circuit cleanly.
 *
 * For a fresh install the wizard ships the v0.1 default
 * ``{research, work, personal}`` triple, so the visual output is the
 * same three cards (research / work / blank). The change is
 * structural — once a user adds a custom domain via Settings →
 * Domains and re-enters setup (or installs against an existing
 * config), their list flows in automatically.
 *
 * The visual pattern (radio cards with separate label + description)
 * follows the WAI-ARIA "card as button" guidance from issue #42 — no
 * concatenated accessible name.
 */

/** Sentinel for the "Blank" card. Picked so it can't collide with a
 *  real domain slug — the D2 slug rules forbid leading/trailing
 *  underscores. */
export const BLANK_THEME = "__blank__";

export interface StartingThemeStepProps {
  pick: string;
  onPick: (key: string) => void;
}

// Per-built-in description copy. Mirrors the v0.1 wording so the
// production UI is unchanged for the default triple. User-added
// slugs fall back to a generic ``"notes for X"`` line.
const BUILTIN_DESCRIPTIONS: Record<string, string> = {
  research: "reading · papers",
  work: "calls · deals",
};

const PRIVACY_RAILED_SLUG = "personal";

export function StartingThemeStep({
  pick,
  onPick,
}: StartingThemeStepProps): React.ReactElement {
  const { domains, loading } = useDomains();
  // Filter ``personal`` out — D5 keeps it privacy-railed and the
  // wizard never seeds it on the user's behalf. If the user adds
  // another privacy-tagged slug in a future version (Plan 11), this
  // filter should grow into a per-domain "seedable" flag.
  const seedableDomains = React.useMemo(
    () => domains.filter((d) => d.slug !== PRIVACY_RAILED_SLUG),
    [domains],
  );

  return (
    <div className="space-y-4">
      <h1 className="text-3xl font-medium tracking-tight">
        Pick a starting theme.
      </h1>
      <p className="text-base leading-relaxed text-muted-foreground">
        We&apos;ll seed your first domain with a welcome note. You can add
        more anytime.
      </p>
      <div
        role="radiogroup"
        aria-label="Starting theme"
        className="grid grid-cols-2 gap-3 pt-2 sm:grid-cols-4"
      >
        {loading && seedableDomains.length === 0 ? (
          <p
            className="col-span-full text-xs text-muted-foreground"
            data-testid="theme-loading"
          >
            Loading domains…
          </p>
        ) : (
          <>
            {seedableDomains.map((d) => (
              <ThemeCard
                key={d.slug}
                cardKey={d.slug}
                label={d.label}
                desc={BUILTIN_DESCRIPTIONS[d.slug] ?? `notes for ${d.label}`}
                accent={d.accent}
                selected={pick === d.slug}
                onSelect={onPick}
              />
            ))}
            <ThemeCard
              cardKey={BLANK_THEME}
              label="Blank"
              desc="start empty"
              accent="var(--text-dim)"
              selected={pick === BLANK_THEME}
              onSelect={onPick}
            />
          </>
        )}
      </div>
    </div>
  );
}

interface ThemeCardProps {
  cardKey: string;
  label: string;
  desc: string;
  accent: string;
  selected: boolean;
  onSelect: (key: string) => void;
}

function ThemeCard({
  cardKey,
  label,
  desc,
  accent,
  selected,
  onSelect,
}: ThemeCardProps): React.ReactElement {
  // WAI-ARIA "card as button" pattern (issue #42): aria-labelledby
  // points at the title span (most distinguishing identifier),
  // aria-describedby at the description span. Result for SR users:
  // "Research, radio, checked, reading · papers".
  const labelId = `theme-label-${cardKey}`;
  const descId = `theme-desc-${cardKey}`;
  return (
    <button
      type="button"
      role="radio"
      aria-checked={selected}
      aria-labelledby={labelId}
      aria-describedby={descId}
      onClick={() => onSelect(cardKey)}
      className={cn(
        "flex flex-col items-start gap-2 rounded-lg border bg-background p-4 text-left transition-colors",
        "focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring",
        selected
          ? "border-primary ring-1 ring-primary"
          : "border-input hover:border-muted-foreground",
      )}
    >
      <span
        aria-hidden="true"
        className="inline-block h-4 w-4 rounded-full opacity-85"
        style={{ background: accent }}
      />
      <span id={labelId} className="text-sm font-medium">
        {label}
      </span>
      <span id={descId} className="text-xs text-muted-foreground">
        {desc}
      </span>
    </button>
  );
}
